%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------
File.version: "1.0"
Camera.type: "PinHole"

Camera1.fx: 383.607
Camera1.fy: 382.691
Camera1.cx: 324.441
Camera1.cy: 239.964

Camera1.k1: -0.0538553
Camera1.k2: 0.0655353
Camera1.p1: -0.0009069
Camera1.p2: 0.0008568
Camera1.k3: -0.0207382

Camera.width: 640
Camera.height: 480
Camera.fps: 30
Camera.RGB: 1

#--------------------------------------------------------------------------------------------
# IMU Parameters
#--------------------------------------------------------------------------------------------
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [ 0.999995, -0.00316155,  0.00096739, -0.02894,
           0.0031655,  0.999987,  -0.00410818, -0.00753,
          -0.0009544,  0.00411122,  0.999991,  -0.01583,
           0,          0,           0,           1]

IMU.InsertKFsWhenLost: 0
IMU.NoiseGyro: 1e-3
IMU.NoiseAcc: 1e-2
IMU.GyroWalk: 1e-6
IMU.AccWalk: 1e-4
IMU.Frequency: 200.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
ORBextractor.nFeatures: 1250
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
